# Rules for main target
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
